In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import precision_recall_curve, f1_score, confusion_matrix, average_precision_score
from fraud_detection.data.loader import DataHandler
from fraud_detection.core.settings import settings

In [2]:
# Test_original Data
test_original = DataHandler.from_registry(
    "DATA", "processed_dir", "test_original.parquet").load()

# Train_original Data
train_original = DataHandler.from_registry(
    "DATA", "processed_dir", "train_original.parquet").load()

# Train_resampled Data
train_resampled = DataHandler.from_registry(
    "DATA", "processed_dir", "train_resampled.parquet").load()

In [3]:
print("Train (original):", train_original.shape)
print("Train (resampled):", train_resampled.shape)
print("Test (original):", test_original.shape)

print("\nClass distribution (original train):")
print(train_original["class"].value_counts(normalize=True))

print("\nClass distribution (resampled train):")
print(train_resampled["class"].value_counts(normalize=True))

Train (original): (120889, 200)
Train (resampled): (219136, 200)
Test (original): (30223, 200)

Class distribution (original train):
class
0    0.906352
1    0.093648
Name: proportion, dtype: float64

Class distribution (resampled train):
class
0    0.5
1    0.5
Name: proportion, dtype: float64


In [4]:
FEATURES = settings.get("features")

TARGET = FEATURES["target"]


X_train_orig = train_original.drop(columns=[TARGET])
y_train_orig = train_original[TARGET]

X_train_res = train_resampled.drop(columns=[TARGET])
y_train_res = train_resampled[TARGET]

X_test = test_original.drop(columns=[TARGET])
y_test = test_original[TARGET]

In [8]:
from sklearn.linear_model import LogisticRegression

baseline_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",  # extra safety even after SMOTE
    n_jobs=-1,
    random_state=42
)

baseline_model.fit(X_train_res, y_train_res)

d:\10Acadamy\Week 5&6\Tasks\fraud-detection\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)


LogisticRegression(class_weight='balanced', max_iter=1000, n_jobs=-1,
                   random_state=42)

In [10]:
y_pred_lr = baseline_model.predict(X_test)
y_proba_lr = baseline_model.predict_proba(X_test)[:, 1]

print("Logistic Regression Evaluation")
print("F1-score:", f1_score(y_test, y_pred_lr))
print("AUC-PR:", average_precision_score(y_test, y_proba_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))


Logistic Regression Evaluation
F1-score: 0.15924413168643275
AUC-PR: 0.09468831053931057
Confusion Matrix:
 [[11520 15873]
 [ 1212  1618]]


In [11]:
# Predict fraud probabilities
y_proba_lr = baseline_model.predict_proba(X_test)[:, 1]

# Precision–Recall curve
precision, recall, thresholds = precision_recall_curve(y_test, y_proba_lr)

# Remove last point (no threshold associated)
precision = precision[:-1]
recall = recall[:-1]
thresholds = thresholds

# Compute F1-score for each threshold
f1_scores = 2 * (precision * recall) / (precision + recall + 1e-9)

# Select best threshold
best_idx = np.argmax(f1_scores)
best_threshold = thresholds[best_idx]

# Apply optimized threshold
y_pred_lr_opt = (y_proba_lr >= best_threshold).astype(int)

# Evaluation
print("Logistic Regression Evaluation (Optimized Threshold)")
print(f"Best threshold: {best_threshold:.4f}")
print(f"F1-score: {f1_score(y_test, y_pred_lr_opt):.4f}")
print(f"AUC-PR: {average_precision_score(y_test, y_proba_lr):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr_opt))

Logistic Regression Evaluation (Optimized Threshold)
Best threshold: 0.3904
F1-score: 0.1720
AUC-PR: 0.0947
Confusion Matrix:
 [[  792 26601]
 [   61  2769]]


In [12]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=400,              # more trees → stabler probabilities
    max_depth=18,                  # allow slightly more expressiveness
    min_samples_leaf=10,           # smooth leaf probabilities
    min_samples_split=20,          # reduce overfitting after SMOTE
    max_features="sqrt",           # standard + strong default
    bootstrap=True,
    class_weight=None,             # IMPORTANT: no weighting after SMOTE
    n_jobs=-1,
    random_state=42
)

rf_model.fit(X_train_res, y_train_res)

RandomForestClassifier(max_depth=18, min_samples_leaf=10, min_samples_split=20,
                       n_estimators=400, n_jobs=-1, random_state=42)

In [13]:
y_pred_rf = rf_model.predict(X_test)
y_proba_rf = rf_model.predict_proba(X_test)[:, 1]

print("Random Forest Evaluation")
print("F1-score:", f1_score(y_test, y_pred_rf))
print("AUC-PR:", average_precision_score(y_test, y_proba_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

Random Forest Evaluation
F1-score: 0.13416308227326806
AUC-PR: 0.09165506769755731
Confusion Matrix:
 [[20029  7364]
 [ 2097   733]]


In [15]:
from sklearn.model_selection import StratifiedKFold, cross_validate

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {
    "f1": "f1",
    "auc_pr": "average_precision",
}

In [25]:
import xgboost as xgb
from sklearn.metrics import f1_score, average_precision_score, confusion_matrix, precision_recall_curve

# -----------------------------
# 1. Initialize XGBoost classifier
# -----------------------------
xgb_model = xgb.XGBClassifier(
    n_estimators=500,       # More trees for better learning
    max_depth=6,            # Typical starting point
    learning_rate=0.1,      # Step size
    subsample=0.8,          # Random sampling for robustness
    colsample_bytree=0.8,   # Feature sampling
    scale_pos_weight=(y_train_res == 0).sum() / (y_train_res ==
                                                 1).sum(),  # Balance classes after SMOTE
    n_jobs=-1,
    random_state=42,
    eval_metric='logloss',
    use_label_encoder=False
)

# -----------------------------
# 2. Train on resampled data
# -----------------------------
xgb_model.fit(X_train_res, y_train_res)

# -----------------------------
# 3. Predict probabilities on test set
# -----------------------------
y_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]

# -----------------------------
# 4. Optimize threshold based on F1
# -----------------------------
precision, recall, thresholds = precision_recall_curve(y_test, y_proba_xgb)
f1_scores = 2 * (precision[:-1] * recall[:-1]) / \
    (precision[:-1] + recall[:-1] + 1e-9)

best_idx = f1_scores.argmax()
best_threshold = thresholds[best_idx]

y_pred_xgb_opt = (y_proba_xgb >= best_threshold).astype(int)

# -----------------------------
# 5. Evaluation
# -----------------------------
print("XGBoost Evaluation")
print(f"Best threshold: {best_threshold:.4f}")
print(f"F1-score: {f1_score(y_test, y_pred_xgb_opt):.4f}")
print(f"AUC-PR: {average_precision_score(y_test, y_proba_xgb):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb_opt))

d:\10Acadamy\Week 5&6\Tasks\fraud-detection\.venv\Lib\site-packages\xgboost\training.py:199: UserWarning: [20:11:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBoost Evaluation
Best threshold: 0.0162
F1-score: 0.1712
AUC-PR: 0.0948
Confusion Matrix:
 [[    0 27393]
 [    0  2830]]


In [26]:
pos_weight = (y_train_orig == 0).sum() / (y_train_orig == 1).sum()

xgb_model = xgb.XGBClassifier(
    n_estimators=500,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=pos_weight,  # balance original imbalance
    n_jobs=-1,
    random_state=42,
    eval_metric='logloss'
)

xgb_model.fit(X_train_orig, y_train_orig)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=-1,
              num_parallel_tree=None, ...)

In [27]:
# -----------------------------
# 3. Predict probabilities on test set
# -----------------------------
y_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]

# -----------------------------
# 4. Optimize threshold based on F1
# -----------------------------
precision, recall, thresholds = precision_recall_curve(y_test, y_proba_xgb)
f1_scores = 2 * (precision[:-1] * recall[:-1]) / \
    (precision[:-1] + recall[:-1] + 1e-9)

best_idx = f1_scores.argmax()
best_threshold = thresholds[best_idx]

y_pred_xgb_opt = (y_proba_xgb >= best_threshold).astype(int)

# -----------------------------
# 5. Evaluation
# -----------------------------
print("XGBoost Evaluation")
print(f"Best threshold: {best_threshold:.4f}")
print(f"F1-score: {f1_score(y_test, y_pred_xgb_opt):.4f}")
print(f"AUC-PR: {average_precision_score(y_test, y_proba_xgb):.4f}")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb_opt))

XGBoost Evaluation
Best threshold: 0.0887
F1-score: 0.1714
AUC-PR: 0.0963
Confusion Matrix:
 [[   66 27327]
 [    4  2826]]
